(ns cljs-webgl.constants.shader)

(def fragment-shader                  0x8B30)
(def vertex-shader                    0x8B31)
(def max-vertex-attribs               0x8869)
(def max-vertex-uniform-vectors       0x8DFB)
(def max-varying-vectors              0x8DFC)
(def max-combined-texture-image-units 0x8B4D)
(def max-vertex-texture-image-units   0x8B4C)
(def max-texture-image-units          0x8872)
(def max-fragment-uniform-vectors     0x8DFD)
(def shader-type                      0x8B4F)
(def delete-status                    0x8B80)
(def link-status                      0x8B82)
(def validate-status                  0x8B83)
(def attached-shaders                 0x8B85)
(def active-uniforms                  0x8B86)
(def active-attributes                0x8B89)
(def shading-language-version         0x8B8C)
(def current-program                  0x8B8D)
